from PyQt5 import QtCore, QtGui, QtWidgets
from mindy import Mindy
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_mainWindow(object):

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        mainWindow.setEnabled(True)
        mainWindow.resize(630, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(630, 391))
        mainWindow.setMaximumSize(QtCore.QSize(630, 391))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("i.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setWindowOpacity(1.0)
        mainWindow.setStyleSheet("")
        mainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        mainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableImages = QtWidgets.QTableWidget(self.centralwidget)
        self.tableImages.setGeometry(QtCore.QRect(0, 60, 631, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableImages.setFont(font)
        self.tableImages.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableImages.setStyleSheet("")
        self.tableImages.setFrameShape(QtWidgets.QFrame.Box)
        self.tableImages.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableImages.setDragDropOverwriteMode(True)
        self.tableImages.setObjectName("tableImages")
        self.tableImages.setColumnCount(6)
        self.tableImages.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        item.setFont(font)
        self.tableImages.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImages.setItem(0, 0, QTableWidgetItem('0'))
        self.tableImages.setItem(0, 1, QTableWidgetItem('1'))
        self.tableImages.setItem(0, 2, QTableWidgetItem('2'))
        self.tableImages.setItem(0, 3, QTableWidgetItem('3'))
        self.tableImages.setItem(0, 4, QTableWidgetItem('4'))
        self.tableImages.setItem(0, 5, QTableWidgetItem('5'))
        self.tableImages.setItem(1, 0, QTableWidgetItem('0'))
        self.tableImages.setItem(1, 1, QTableWidgetItem('1'))
        self.tableImages.setItem(1, 2, QTableWidgetItem('2'))
        self.tableImages.setItem(1, 3, QTableWidgetItem('3'))
        self.tableImages.setItem(1, 4, QTableWidgetItem('4'))
        self.tableImages.setItem(1, 5, QTableWidgetItem('5'))
        self.inputLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.inputLogin.setGeometry(QtCore.QRect(10, 20, 186, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.inputLogin.setFont(font)
        self.inputLogin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.inputLogin.setAutoFillBackground(False)
        self.inputLogin.setStyleSheet("border-radius: 10px;\n""")
        self.inputLogin.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.inputLogin.setInputMask("")
        self.inputLogin.setText("")
        self.inputLogin.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.inputLogin.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.inputLogin.setClearButtonEnabled(False)
        self.inputLogin.setObjectName("inputLogin")
        self.buttonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLogin.setGeometry(QtCore.QRect(210, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonLogin.setFont(font)
        self.buttonLogin.setStyleSheet("")
        self.buttonLogin.setObjectName("buttonLogin")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 350, 651, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 360, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(60, 360, 20, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.labelStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(80, 360, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelStatus.setFont(font)
        self.labelStatus.setStyleSheet("color: red;")
        self.labelStatus.setObjectName("labelStatus")

        self.labelAdderId = QtWidgets.QLabel(self.centralwidget)
        self.labelAdderId.setFont(font)
        self.labelAdderId.setText('')
        self.labelAdderId.setGeometry(QtCore.QRect(580, 360, 431, 31))

        self.inputDate = QtWidgets.QDateEdit(self.centralwidget)
        self.inputDate.setGeometry(QtCore.QRect(480, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.inputDate.setFont(font)
        self.inputDate.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.inputDate.setAcceptDrops(False)
        # self.inputDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.inputDate.setDisplayFormat('yyyy-MM-dd')
        self.inputDate.setDateTime(QtCore.QDateTime.currentDateTime())
        self.inputDate.setObjectName("inputDate")
        self.inputDate.setSelectedSection(QtWidgets.QDateTimeEdit.DaySection)
        self.buttonGetImages = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGetImages.setEnabled(False)
        self.buttonGetImages.setGeometry(QtCore.QRect(350, 20, 121, 31))
        self.buttonGetImages.setObjectName("buttonGetImages")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 260, 171, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.inputQa = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.inputQa.setMinimum(0)
        self.inputQa.setMaximum(5)
        self.inputQa.setObjectName("inputQa")
        self.intValid = QtGui.QIntValidator()
        self.gridLayout.addWidget(self.inputQa, 1, 1, 1, 1)
        self.inputPt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.inputPt.setObjectName("inputPt")
        # self.inputPt.setValidator(self.intValid)
        self.gridLayout.addWidget(self.inputPt, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.buttonChange = QtWidgets.QPushButton(self.centralwidget)
        self.buttonChange.setGeometry(QtCore.QRect(200, 290, 121, 31))
        self.buttonChange.setObjectName("buttonChange")
        mainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.inputLogin, self.buttonLogin)
        mainWindow.setTabOrder(self.buttonLogin, self.inputDate)
        self.mindy = Mindy(self)

        self.setTextStatusConnection()
        self.addEvent()

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Eazy Program Time"))
        item = self.tableImages.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "ID image"))
        item = self.tableImages.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Image"))
        item = self.tableImages.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Pt"))
        item = self.tableImages.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Qa"))
        item = self.tableImages.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "App"))
        item = self.tableImages.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Status"))

        self.buttonLogin.setText(_translate("mainWindow", "Ввойти"))
        self.label.setText(_translate("mainWindow", "Status:"))
        self.labelStatus.setText(_translate("mainWindow", "Error contection"))
        self.buttonGetImages.setText(_translate("mainWindow", "Загрузить изоб."))
        self.label_3.setText(_translate("mainWindow", "QA:"))
        self.label_2.setText(_translate("mainWindow", "PT:"))
        self.buttonChange.setText(_translate("mainWindow", "Сменить"))

    def setTextStatusConnection(self):

        if self.mindy.getStatusConnection():
            self.labelStatus.setText('Connected')
            self.labelStatus.setStyleSheet('color: green;')
        else:
            self.labelStatus.setText('Error connection')
            self.labelStatus.setStyleSheet('color: red;')
    
    def addEvent(self):
        self.buttonLogin.clicked.connect(lambda: self.mindy.loginIn(self.inputLogin.text()))
        self.buttonGetImages.clicked.connect(lambda: self.mindy.getListImages())
        self.buttonChange.clicked.connect(lambda: self.mindy.changeData())
        self.tableImages.clicked.connect(lambda: self.mindy.getItems())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())